export type CompletionShell = 'bash' | 'zsh' | 'fish';

const FLAGS = [
  '-u',
  '--url',
  '--urls',
  '--sitemap',
  '--crawl',
  '--max-urls',
  '--max-depth',
  '--max-crawl-page-bytes',
  '--max-crawl-bytes',
  '--concurrency',
  '--watch',
  '--timeout',
  '--wait-until',
  '--settle-ms',
  '--geo-sitemap',
  '--geo-sitemap-max-urls',
  '--geo-path-depth',
  '-o',
  '--output',
  '--comparison-output',
  '--geo-summary-output',
  '--geo-summary-csv',
  '--geo-entity-variants-csv',
  '--geo-crawler-access-csv',
  '--geo-comparison-csv',
  '--geo-gate-output',
  '--fail-on-geo-change-signal',
  '--fail-on-geo-change-url',
  '--render',
  '--html',
  '--pdf',
  '--history',
  '--history-report',
  '--junit',
  '--sarif',
  '--markdown',
  '--csv',
  '--bing-ai-csv',
  '--bing-ai-xlsx',
  '--bing-ai-baseline-csv',
  '--bing-ai-baseline-xlsx',
  '--bing-ai-query-baseline-csv',
  '--bing-ai-query-baseline-xlsx',
  '--bing-ai-topic-baseline-csv',
  '--bing-ai-topic-baseline-xlsx',
  '--google-ai-csv',
  '--google-ai-xlsx',
  '--google-ai-discover-csv',
  '--google-ai-discover-xlsx',
  '--google-ai-baseline-csv',
  '--google-ai-baseline-xlsx',
  '--google-ai-dimension-baseline-csv',
  '--google-ai-dimension-baseline-xlsx',
  '--geo-google-ai-citation-concordance-csv',
  '--geo-google-ai-citation-concordance-provider-csv',
  '--geo-google-ai-citation-concordance-html',
  '--geo-google-ai-citation-concordance-path-family-csv',
  '--geo-google-ai-citation-concordance-path-depth-sweep-csv',
  '--geo-google-ai-citation-concordance-baseline-json',
  '--geo-google-ai-citation-concordance-comparison-csv',
  '--geo-google-ai-citation-concordance-comparison-json',
  '--geo-google-ai-citation-concordance-comparison-html',
  '--geo-google-ai-citation-concordance-provider-comparison-csv',
  '--geo-google-ai-citation-concordance-path-depth',
  '--geo-google-surface-matrix',
  '--geo-google-surface-baseline-json',
  '--geo-google-surface-path-family-csv',
  '--geo-platform-matrix',
  '--geo-platform-baseline-json',
  '--geo-audit-json',
  '--geo-audit-baseline-json',
  '--geo-crawler-log',
  '--geo-crawler-path-families-csv',
  '--geo-crawler-path-families-json',
  '--geo-crawler-path-families-html',
  '--geo-crawler-path-family-audit-csv',
  '--geo-crawler-path-family-audit-json',
  '--geo-crawler-path-family-audit-html',
  '--geo-crawler-path-family-audit-comparison-csv',
  '--geo-crawler-path-family-audit-comparison-json',
  '--geo-crawler-path-family-audit-comparison-html',
  '--geo-crawler-path-family-comparison-csv',
  '--geo-crawler-path-family-comparison-json',
  '--geo-crawler-path-family-comparison-html',
  '--geo-crawler-path-family-failure-gate-json',
  '--geo-crawler-path-depth',
  '--geo-crawler-token',
  '--geo-crawler-ip-ranges',
  '--geo-ai-referral-source',
  '--geo-answer-observations',
  '--geo-answer-baseline-observations',
  '--geo-answer-comparison-csv',
  '--geo-answer-provider-position-comparison-csv',
  '--geo-answer-cohorts-csv',
  '--geo-answer-cohort-comparison-csv',
  '--geo-answer-provider-pairs-csv',
  '--geo-answer-provider-prompt-overlap-csv',
  '--geo-answer-provider-prompt-source-overlap-csv',
  '--geo-answer-sample-mix-csv',
  '--geo-answer-cohort-period-standardization-csv',
  '--geo-answer-prompt-sampling-plan-csv',
  '--geo-answer-prompt-sampling-plan-json',
  '--geo-answer-prompt-plan-provider-pairs-csv',
  '--geo-answer-execution-context-csv',
  '--geo-answer-execution-context-coverage-csv',
  '--geo-answer-execution-context-comparison-csv',
  '--geo-answer-execution-context-trends-csv',
  '--geo-answer-length-profiles-csv',
  '--geo-answer-length-comparison-csv',
  '--geo-answer-length-trends-csv',
  '--geo-answer-prompt-plan-min-prompts',
  '--geo-answer-prompt-plan-owned-reach-margin',
  '--geo-answer-prompt-plan-min-jaccard',
  '--geo-answer-prompt-plan-max-paired-groups',
  '--geo-answer-prompt-plan-max-total-paired-groups',
  '--geo-answer-prompt-plan-total-allocation',
  '--geo-answer-prompt-plan-cohort-targets',
  '--geo-answer-cohort-standardization-csv',
  '--geo-answer-stability-csv',
  '--geo-answer-source-persistence-csv',
  '--geo-answer-citation-url-persistence-csv',
  '--geo-answer-cohort-trends-csv',
  '--geo-answer-audit-signals-csv',
  '--geo-answer-audited-owned-page-provider-inventory-csv',
  '--geo-answer-audited-owned-page-provider-inventory-html',
  '--geo-answer-audited-owned-page-provider-inventory-comparison-csv',
  '--geo-answer-audited-owned-page-provider-inventory-comparison-html',
  '--geo-answer-audited-owned-page-provider-inventory-comparison-json',
  '--geo-answer-audited-owned-pages-csv',
  '--geo-answer-audited-owned-page-comparison-csv',
  '--geo-answer-audited-owned-page-providers-csv',
  '--geo-answer-audited-owned-page-provider-comparison-csv',
  '--geo-answer-source-category',
  '--geo-answer-source-categories-csv',
  '--geo-answer-source-category-mapping-audit-csv',
  '--geo-answer-source-category-comparison-csv',
  '--geo-answer-source-category-mix-decomposition-csv',
  '--geo-answer-source-category-mix-decomposition-html',
  '--geo-answer-source-category-concentration-trends-csv',
  '--geo-answer-source-category-concentration-trends-html',
  '--geo-answer-source-category-share-trends-csv',
  '--geo-answer-source-category-share-trends-html',
  '--geo-answer-source-category-monthly-gates-json',
  '--fail-on-geo-answer-source-category-monthly-jsd-above',
  '--fail-on-geo-answer-source-category-monthly-hhi-rise-above',
  '--fail-on-geo-answer-source-category-monthly-top-three-hhi-rise-above',
  '--fail-on-geo-answer-source-category-monthly-hhi-above',
  '--fail-on-geo-answer-source-category-monthly-top-three-hhi-above',
  '--fail-on-geo-answer-source-category-monthly-min-events',
  '--fail-on-geo-answer-source-category-prompt-balanced-jsd-lower-ci-above',
  '--fail-on-geo-answer-source-category-prompt-balanced-jsd-min-prompts',
  '--geo-answer-source-category-prompt-balanced-jsd-gate-json',
  '--fail-on-geo-answer-source-category-share-drop',
  '--geo-answer-source-category-prompt-coverage-csv',
  '--geo-answer-source-category-prompt-details-csv',
  '--geo-answer-source-category-trends-csv',
  '--geo-answer-source-category-provider-pairs-csv',
  '--geo-answer-source-category-cooccurrence-csv',
  '--geo-answer-source-category-path-families-csv',
  '--geo-answer-source-category-path-family-comparison-csv',
  '--geo-answer-citation-positions-csv',
  '--geo-answer-domain-prompt-coverage-csv',
  '--geo-answer-source-rarefaction-csv',
  '--geo-answer-prompt-family-source-rarefaction-csv',
  '--geo-answer-prompt-family-source-rarefaction-html',
  '--geo-answer-prompt-family-source-rarefaction-sweep-csv',
  '--geo-answer-prompt-family-source-rarefaction-sweep-html',
  '--geo-answer-provider-prompt-family-source-overlap-csv',
  '--geo-answer-provider-prompt-family-source-overlap-html',
  '--geo-answer-provider-prompt-family-source-overlap-sweep-csv',
  '--geo-answer-provider-prompt-family-source-overlap-sweep-html',
  '--geo-answer-prompt-family-period-comparison-csv',
  '--geo-answer-prompt-family-period-comparison-html',
  '--geo-answer-prompt-family-period-comparison-sweep-csv',
  '--geo-answer-prompt-family-period-comparison-sweep-summary-csv',
  '--geo-answer-prompt-family-period-comparison-sweep-html',
  '--geo-answer-source-rarefaction-batch-size',
  '--geo-answer-domain-prompt-coverage-comparison-csv',
  '--geo-answer-domain-paired-reach-comparison-csv',
  '--geo-answer-domain-paired-reach-comparison-json',
  '--fail-on-geo-answer-domain-paired-reach-drop',
  '--fail-on-geo-answer-domain-paired-reach-alpha',
  '--fail-on-geo-answer-domain-paired-reach-min-prompts',
  '--geo-answer-domain-paired-reach-gate-json',
  '--geo-answer-page-paired-reach-comparison-csv',
  '--geo-answer-page-paired-reach-comparison-json',
  '--geo-answer-page-opportunities-csv',
  '--geo-answer-page-opportunity-trends-csv',
  '--geo-answer-page-opportunity-path-families-csv',
  '--geo-answer-page-opportunity-path-family-depth-sweep-csv',
  '--geo-answer-page-opportunity-path-family-depth-sweep-html',
  '--geo-answer-page-opportunity-path-family-trends-csv',
  '--geo-answer-page-opportunity-path-family-trends-html',
  '--geo-answer-page-opportunity-path-depth',
  '--fail-on-geo-answer-page-opportunity-path-family-monthly-rise',
  '--fail-on-geo-answer-page-opportunity-path-family-monthly-alpha',
  '--fail-on-geo-answer-page-opportunity-path-family-monthly-min-prompts',
  '--geo-answer-page-opportunity-path-family-monthly-gate-json',
  '--fail-on-geo-answer-page-opportunity-monthly-rise',
  '--fail-on-geo-answer-page-opportunity-monthly-alpha',
  '--fail-on-geo-answer-page-opportunity-monthly-min-prompts',
  '--geo-answer-page-opportunity-monthly-gate-json',
  '--geo-answer-page-paired-reach-owned-only',
  '--fail-on-geo-answer-page-paired-reach-drop',
  '--fail-on-geo-answer-page-paired-reach-alpha',
  '--fail-on-geo-answer-page-paired-reach-min-prompts',
  '--geo-answer-page-paired-reach-metric',
  '--geo-answer-page-paired-reach-gate-json',
  '--geo-answer-source-diversity-uncertainty-csv',
  '--geo-answer-source-diversity-uncertainty-html',
  '--geo-answer-source-diversity-comparison-csv',
  '--geo-answer-source-diversity-comparison-html',
  '--geo-answer-provider-source-divergence-csv',
  '--geo-answer-source-portfolio-drift-csv',
  '--geo-answer-source-portfolio-drift-html',
  '--geo-answer-source-portfolio-drift-json',
  '--geo-answer-source-portfolio-attribution-csv',
  '--geo-answer-source-portfolio-attribution-json',
  '--geo-answer-source-portfolio-attribution-html',
  '--geo-answer-owned-source-share-gate-csv',
  '--geo-answer-owned-source-share-gate-json',
  '--geo-answer-source-network-csv',
  '--geo-answer-source-network-comparison-csv',
  '--geo-answer-rank-weighted-source-network-csv',
  '--geo-answer-rank-weighted-source-network-comparison-csv',
  '--geo-answer-source-network-html',
  '--geo-answer-source-network-comparison-html',
  '--geo-answer-provider-source-network-overlap-csv',
  '--geo-answer-provider-source-network-edge-drift-csv',
  '--geo-answer-provider-source-network-edge-drift-html',
  '--geo-answer-provider-source-network-edge-comparison-csv',
  '--geo-answer-provider-source-network-edge-html',
  '--geo-answer-owned-source-network-gaps-csv',
  '--geo-answer-prompt-similarity-csv',
  '--geo-answer-prompt-families-csv',
  '--geo-answer-prompt-families-html',
  '--geo-answer-prompt-family-influence-csv',
  '--geo-answer-prompt-family-influence-html',
  '--geo-answer-prompt-family-threshold-sweep-csv',
  '--geo-answer-prompt-family-threshold-sweep-html',
  '--geo-answer-prompt-similarity-threshold',
  '--geo-answer-prompt-family-threshold',
  '--geo-answer-citation-date-alignment-csv',
  '--geo-answer-owned-rank-csv',
  '--geo-answer-owned-prompt-coverage-csv',
  '--geo-answer-owned-prompt-reach-period-csv',
  '--geo-answer-owned-prompt-opportunities-csv',
  '--geo-answer-competitive-gaps-csv',
  '--geo-answer-provider-owned-gaps-csv',
  '--geo-answer-provider-owned-gap-comparison-csv',
  '--geo-answer-competitive-gap-comparison-csv',
  '--geo-answer-owned-rank-comparison-csv',
  '--geo-answer-owned-prompt-rank-comparison-csv',
  '--geo-answer-co-citation-csv',
  '--geo-answer-co-citation-comparison-csv',
  '--geo-answer-entity',
  '--geo-answer-entity-mentions-csv',
  '--geo-answer-entity-prompt-details-csv',
  '--geo-answer-entity-prompt-provider-pairs-csv',
  '--geo-answer-entity-prompt-comparison-csv',
  '--geo-answer-entity-co-mentions-csv',
  '--geo-answer-entity-co-mention-comparison-csv',
  '--geo-answer-entity-citation-domains-csv',
  '--geo-answer-entity-citation-pages-csv',
  '--geo-answer-entity-source-categories-csv',
  '--geo-answer-entity-source-category-comparison-csv',
  '--geo-answer-entity-citation-domain-comparison-csv',
  '--geo-answer-entity-citation-page-comparison-csv',
  '--geo-answer-entity-citation-position-comparison-csv',
  '--geo-answer-entity-opportunities-csv',
  '--geo-answer-entity-prompt-matched-association-csv',
  '--geo-answer-entity-prompt-matched-association-html',
  '--geo-answer-entity-path-families-csv',
  '--geo-answer-entity-path-family-monthly-csv',
  '--geo-answer-entity-path-family-comparison-csv',
  '--geo-answer-path-family-csv',
  '--geo-answer-path-family-cohorts-csv',
  '--geo-answer-path-family-trends-csv',
  '--geo-answer-path-family-cohort-comparison-csv',
  '--geo-answer-path-family-comparison-csv',
  '--geo-answer-crawler-report',
  '--geo-answer-crawler-origin',
  '--geo-answer-crawler-matches-csv',
  '--geo-answer-path-depth',
  '--geo-answer-owned-domain',
  '--geo-crawler-origin',
  '--geo-crawler-sitemap',
  '--geo-crawler-sitemap-max-urls',
  '--geo-robots-txt',
  '--geo-robots-baseline-txt',
  '--geo-robots-origin',
  '--geo-robots-sitemap',
  '--geo-robots-token',
  '--fail-on-findings',
  '--fail-on-newly-blocked-geo-paths',
  '--fail-on-newly-blocked-geo-audit-pages',
  '--fail-on-newly-blocked-geo-targets',
  '--fail-on-new-ai-referral-failures',
  '--fail-on-ai-crawler-timing-regression',
  '--fail-on-geo-crawler-path-family-failure-rise',
  '--fail-on-ai-crawler-cloudfront-result-regression',
  '--fail-on-duplicate-metadata',
  '--fail-on-duplicate-content',
  '--fail-on-hreflang',
  '--fail-on-canonical-chains',
  '--fail-below-score',
  '--fail-on-geo-crawler-path-family-failure-rise',
  '--fail-on-geo-answer-owned-citation-drop',
  '--fail-on-geo-answer-owned-source-share-drop',
  '--fail-on-geo-answer-owned-source-share-drop-lower-ci',
  '--fail-on-geo-answer-owned-source-share-sign-test-alpha',
  '--fail-on-geo-answer-owned-source-share-min-prompts',
  '--fail-on-geo-answer-owned-reach-bound-drop',
  '--fail-on-geo-answer-unknown-owned-observation-share',
  '--fail-on-geo-answer-unknown-owned-prompt-share',
  '--fail-on-geo-answer-unknown-owned-state-share-rise',
  '--fail-on-geo-answer-provider-balanced-citation-drop',
  '--fail-on-geo-answer-owned-top-three-drop',
  '--fail-on-geo-answer-owned-first-position-drop',
  '--fail-on-geo-answer-owned-prompt-balanced-first-position-drop',
  '--fail-on-geo-answer-owned-prompt-balanced-first-position-drop-lower-ci',
  '--fail-on-geo-answer-owned-prompt-balanced-top-three-drop',
  '--fail-on-geo-answer-owned-prompt-balanced-top-three-drop-lower-ci',
  '--fail-on-geo-answer-owned-prompt-balanced-rank-min-matched-prompts',
  '--fail-on-geo-answer-owned-prompt-balanced-mrr-drop',
  '--fail-on-geo-answer-owned-prompt-balanced-mrr-drop-lower-ci',
  '--fail-on-geo-answer-length-owned-top-three-drop',
  '--fail-on-geo-answer-length-owned-top-three-drop-lower-ci',
  '--fail-on-geo-answer-length-owned-first-position-drop',
  '--fail-on-geo-answer-length-owned-first-position-drop-lower-ci',
  '--fail-on-geo-answer-length-owned-mrr-drop',
  '--fail-on-geo-answer-length-owned-mrr-drop-lower-ci',
  '--fail-on-geo-answer-length-owned-rank-min-matched-prompts',
  '--fail-on-geo-answer-entity-mention-drop',
  '--fail-on-geo-answer-entity-owned-top-three-drop',
  '--fail-on-geo-answer-path-family-coverage-drop',
  '--fail-on-geo-answer-path-family-prompt-coverage-drop',
  '--fail-on-geo-answer-path-family-over-index-drop',
  '--fail-on-geo-answer-entity-path-family-prompt-coverage-drop',
  '--fail-on-geo-answer-entity-path-family-top-three-drop',
  '--fail-on-geo-answer-entity-citation-page-prompt-coverage-drop',
  '--fail-on-geo-answer-entity-citation-page-top-three-drop',
  '--fail-on-geo-answer-entity-prompt-mention-drop',
  '--fail-on-geo-answer-entity-prompt-balanced-mention-drop',
  '--fail-on-geo-answer-entity-prompt-min-matched-prompts',
  '--fail-on-geo-answer-provider-prompt-overlap-below',
  '--fail-on-geo-answer-provider-min-prompts',
  '--fail-on-geo-answer-provider-min-matched-prompts',
  '--fail-on-geo-answer-owned-prompt-coverage-drop',
  '--fail-on-geo-answer-cohort-owned-prompt-coverage-drop',
  '--fail-on-geo-answer-cohort-owned-mrr-drop',
  '--fail-on-geo-answer-cohort-owned-mrr-min-prompts',
  '--fail-on-geo-answer-cohort-monthly-owned-mrr-drop',
  '--fail-on-geo-answer-cohort-monthly-owned-mrr-min-prompts',
  '--fail-on-geo-answer-cohort-monthly-paired-mrr-drop',
  '--fail-on-geo-answer-cohort-monthly-paired-mrr-drop-lower-ci',
  '--fail-on-geo-answer-cohort-monthly-paired-mrr-min-matched-prompts',
  '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop',
  '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop-lower-ci',
  '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-decline',
  '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-alpha',
  '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-min-matched-prompts',
  '--fail-on-geo-answer-sample-mix-divergence',
  '--fail-on-geo-answer-cohort-standardized-citation-drop',
  '--fail-on-geo-answer-cohort-standardized-owned-prompt-coverage-drop',
  '--fail-on-geo-answer-prompt-plan-miss',
  '--baseline',
  '--fail-on-regression',
  '--fail-on-geo-change',
  '--fail-on-geo-change-signal',
  '--fail-on-geo-change-url',
  '--fail-on-geo-change-transition',
  '--category',
  '--json',
  '-c',
  '--config',
  '-p',
  '--preset',
  '--headed',
  '--viewport',
  '--init-config',
  '--doctor',
  '-v',
  '--verbose',
  '-h',
  '--help',
  '-V',
  '--version',
  '--completion',
];

const FILE_OPTIONS = [
  '--urls',
  '-o',
  '--output',
  '--comparison-output',
  '--geo-summary-output',
  '--geo-summary-csv',
  '--geo-entity-variants-csv',
  '--geo-crawler-access-csv',
  '--geo-comparison-csv',
  '--geo-gate-output',
  '--render',
  '--html',
  '--pdf',
  '--history',
  '--history-report',
  '--junit',
  '--sarif',
  '--markdown',
  '--csv',
  '--bing-ai-csv',
  '--bing-ai-xlsx',
  '--bing-ai-baseline-csv',
  '--bing-ai-baseline-xlsx',
  '--bing-ai-query-baseline-csv',
  '--bing-ai-query-baseline-xlsx',
  '--bing-ai-topic-baseline-csv',
  '--bing-ai-topic-baseline-xlsx',
  '--google-ai-csv',
  '--google-ai-xlsx',
  '--google-ai-discover-csv',
  '--google-ai-discover-xlsx',
  '--google-ai-baseline-csv',
  '--google-ai-baseline-xlsx',
  '--google-ai-dimension-baseline-csv',
  '--google-ai-dimension-baseline-xlsx',
  '--geo-google-ai-citation-concordance-csv',
  '--geo-google-ai-citation-concordance-provider-csv',
  '--geo-google-ai-citation-concordance-html',
  '--geo-google-ai-citation-concordance-path-family-csv',
  '--geo-google-ai-citation-concordance-path-depth-sweep-csv',
  '--geo-google-ai-citation-concordance-baseline-json',
  '--geo-google-ai-citation-concordance-comparison-csv',
  '--geo-google-ai-citation-concordance-comparison-json',
  '--geo-google-ai-citation-concordance-comparison-html',
  '--geo-google-ai-citation-concordance-provider-comparison-csv',
  '--geo-google-ai-citation-concordance-path-depth',
  '--geo-google-surface-baseline-json',
  '--geo-google-surface-path-family-csv',
  '--geo-platform-baseline-json',
  '--geo-audit-json',
  '--geo-audit-baseline-json',
  '--geo-crawler-log',
  '--geo-crawler-path-families-csv',
  '--geo-crawler-path-families-json',
  '--geo-crawler-path-families-html',
  '--geo-crawler-path-family-audit-csv',
  '--geo-crawler-path-family-audit-json',
  '--geo-crawler-path-family-audit-html',
  '--geo-crawler-path-family-audit-comparison-csv',
  '--geo-crawler-path-family-audit-comparison-json',
  '--geo-crawler-path-family-audit-comparison-html',
  '--geo-crawler-path-family-comparison-csv',
  '--geo-crawler-path-family-comparison-json',
  '--geo-crawler-path-family-comparison-html',
  '--geo-crawler-path-family-failure-gate-json',
  '--geo-crawler-ip-ranges',
  '--geo-answer-observations',
  '--geo-answer-baseline-observations',
  '--geo-answer-comparison-csv',
  '--geo-answer-provider-position-comparison-csv',
  '--geo-answer-cohorts-csv',
  '--geo-answer-cohort-comparison-csv',
  '--geo-answer-provider-pairs-csv',
  '--geo-answer-provider-prompt-overlap-csv',
  '--geo-answer-provider-prompt-source-overlap-csv',
  '--geo-answer-sample-mix-csv',
  '--geo-answer-cohort-period-standardization-csv',
  '--geo-answer-prompt-sampling-plan-csv',
  '--geo-answer-prompt-sampling-plan-json',
  '--geo-answer-prompt-plan-provider-pairs-csv',
  '--geo-answer-execution-context-csv',
  '--geo-answer-execution-context-coverage-csv',
  '--geo-answer-execution-context-comparison-csv',
  '--geo-answer-execution-context-trends-csv',
  '--geo-answer-length-profiles-csv',
  '--geo-answer-length-comparison-csv',
  '--geo-answer-length-trends-csv',
  '--geo-answer-prompt-plan-cohort-targets',
  '--geo-answer-cohort-standardization-csv',
  '--geo-answer-stability-csv',
  '--geo-answer-source-persistence-csv',
  '--geo-answer-citation-url-persistence-csv',
  '--geo-answer-cohort-trends-csv',
  '--geo-answer-audit-signals-csv',
  '--geo-answer-audited-owned-page-provider-inventory-csv',
  '--geo-answer-audited-owned-page-provider-inventory-html',
  '--geo-answer-audited-owned-page-provider-inventory-comparison-csv',
  '--geo-answer-audited-owned-page-provider-inventory-comparison-html',
  '--geo-answer-audited-owned-page-provider-inventory-comparison-json',
  '--geo-answer-audited-owned-pages-csv',
  '--geo-answer-audited-owned-page-comparison-csv',
  '--geo-answer-audited-owned-page-providers-csv',
  '--geo-answer-audited-owned-page-provider-comparison-csv',
  '--geo-answer-source-category',
  '--geo-answer-source-categories-csv',
  '--geo-answer-source-category-mapping-audit-csv',
  '--geo-answer-source-category-comparison-csv',
  '--geo-answer-source-category-mix-decomposition-csv',
  '--geo-answer-source-category-mix-decomposition-html',
  '--geo-answer-source-category-concentration-trends-csv',
  '--geo-answer-source-category-concentration-trends-html',
  '--geo-answer-source-category-share-trends-csv',
  '--geo-answer-source-category-share-trends-html',
  '--geo-answer-source-category-monthly-gates-json',
  '--fail-on-geo-answer-source-category-monthly-jsd-above',
  '--fail-on-geo-answer-source-category-monthly-hhi-rise-above',
  '--fail-on-geo-answer-source-category-monthly-top-three-hhi-rise-above',
  '--fail-on-geo-answer-source-category-monthly-hhi-above',
  '--fail-on-geo-answer-source-category-monthly-top-three-hhi-above',
  '--fail-on-geo-answer-source-category-monthly-min-events',
  '--fail-on-geo-answer-source-category-prompt-balanced-jsd-lower-ci-above',
  '--fail-on-geo-answer-source-category-prompt-balanced-jsd-min-prompts',
  '--geo-answer-source-category-prompt-balanced-jsd-gate-json',
  '--fail-on-geo-answer-source-category-share-drop',
  '--geo-answer-source-category-prompt-coverage-csv',
  '--geo-answer-source-category-prompt-details-csv',
  '--geo-answer-source-category-trends-csv',
  '--geo-answer-source-category-provider-pairs-csv',
  '--geo-answer-source-category-cooccurrence-csv',
  '--geo-answer-source-category-path-families-csv',
  '--geo-answer-source-category-path-family-comparison-csv',
  '--geo-answer-citation-positions-csv',
  '--geo-answer-domain-prompt-coverage-csv',
  '--geo-answer-source-rarefaction-csv',
  '--geo-answer-prompt-family-source-rarefaction-csv',
  '--geo-answer-prompt-family-source-rarefaction-html',
  '--geo-answer-prompt-family-source-rarefaction-sweep-csv',
  '--geo-answer-prompt-family-source-rarefaction-sweep-html',
  '--geo-answer-provider-prompt-family-source-overlap-csv',
  '--geo-answer-provider-prompt-family-source-overlap-html',
  '--geo-answer-provider-prompt-family-source-overlap-sweep-csv',
  '--geo-answer-provider-prompt-family-source-overlap-sweep-html',
  '--geo-answer-prompt-family-period-comparison-csv',
  '--geo-answer-prompt-family-period-comparison-html',
  '--geo-answer-prompt-family-period-comparison-sweep-csv',
  '--geo-answer-prompt-family-period-comparison-sweep-summary-csv',
  '--geo-answer-prompt-family-period-comparison-sweep-html',
  '--geo-answer-domain-prompt-coverage-comparison-csv',
  '--geo-answer-domain-paired-reach-comparison-csv',
  '--geo-answer-domain-paired-reach-comparison-json',
  '--fail-on-geo-answer-domain-paired-reach-drop',
  '--fail-on-geo-answer-domain-paired-reach-alpha',
  '--fail-on-geo-answer-domain-paired-reach-min-prompts',
  '--geo-answer-domain-paired-reach-gate-json',
  '--geo-answer-page-paired-reach-comparison-csv',
  '--geo-answer-page-paired-reach-comparison-json',
  '--geo-answer-page-opportunities-csv',
  '--geo-answer-page-paired-reach-gate-json',
  '--geo-answer-source-diversity-uncertainty-csv',
  '--geo-answer-source-diversity-uncertainty-html',
  '--geo-answer-source-diversity-comparison-csv',
  '--geo-answer-source-diversity-comparison-html',
  '--geo-answer-provider-source-divergence-csv',
  '--geo-answer-source-portfolio-drift-csv',
  '--geo-answer-source-portfolio-drift-html',
  '--geo-answer-source-portfolio-drift-json',
  '--geo-answer-source-portfolio-attribution-csv',
  '--geo-answer-source-portfolio-attribution-json',
  '--geo-answer-source-portfolio-attribution-html',
  '--geo-answer-owned-source-share-gate-csv',
  '--geo-answer-owned-source-share-gate-json',
  '--geo-answer-source-network-csv',
  '--geo-answer-source-network-comparison-csv',
  '--geo-answer-rank-weighted-source-network-csv',
  '--geo-answer-rank-weighted-source-network-comparison-csv',
  '--geo-answer-source-network-html',
  '--geo-answer-source-network-comparison-html',
  '--geo-answer-provider-source-network-overlap-csv',
  '--geo-answer-provider-source-network-edge-drift-csv',
  '--geo-answer-provider-source-network-edge-drift-html',
  '--geo-answer-provider-source-network-edge-comparison-csv',
  '--geo-answer-provider-source-network-edge-html',
  '--geo-answer-owned-source-network-gaps-csv',
  '--geo-answer-prompt-similarity-csv',
  '--geo-answer-prompt-families-csv',
  '--geo-answer-prompt-families-html',
  '--geo-answer-prompt-family-influence-csv',
  '--geo-answer-prompt-family-influence-html',
  '--geo-answer-prompt-family-threshold-sweep-csv',
  '--geo-answer-prompt-family-threshold-sweep-html',
  '--geo-answer-citation-date-alignment-csv',
  '--geo-answer-owned-rank-csv',
  '--geo-answer-owned-prompt-coverage-csv',
  '--geo-answer-owned-prompt-reach-period-csv',
  '--geo-answer-owned-prompt-opportunities-csv',
  '--geo-answer-competitive-gaps-csv',
  '--geo-answer-provider-owned-gaps-csv',
  '--geo-answer-provider-owned-gap-comparison-csv',
  '--geo-answer-competitive-gap-comparison-csv',
  '--geo-answer-owned-rank-comparison-csv',
  '--geo-answer-owned-prompt-rank-comparison-csv',
  '--geo-answer-co-citation-csv',
  '--geo-answer-co-citation-comparison-csv',
  '--geo-answer-entity-mentions-csv',
  '--geo-answer-entity-prompt-details-csv',
  '--geo-answer-entity-prompt-provider-pairs-csv',
  '--geo-answer-entity-prompt-comparison-csv',
  '--geo-answer-entity-co-mentions-csv',
  '--geo-answer-entity-co-mention-comparison-csv',
  '--geo-answer-entity-citation-domains-csv',
  '--geo-answer-entity-citation-pages-csv',
  '--geo-answer-entity-source-categories-csv',
  '--geo-answer-entity-source-category-comparison-csv',
  '--geo-answer-entity-citation-domain-comparison-csv',
  '--geo-answer-entity-citation-page-comparison-csv',
  '--geo-answer-entity-citation-position-comparison-csv',
  '--geo-answer-entity-opportunities-csv',
  '--geo-answer-entity-prompt-matched-association-csv',
  '--geo-answer-entity-prompt-matched-association-html',
  '--geo-answer-entity-path-families-csv',
  '--geo-answer-entity-path-family-monthly-csv',
  '--geo-answer-entity-path-family-comparison-csv',
  '--geo-answer-path-family-csv',
  '--geo-answer-path-family-cohorts-csv',
  '--geo-answer-path-family-trends-csv',
  '--geo-answer-path-family-cohort-comparison-csv',
  '--geo-answer-path-family-comparison-csv',
  '--geo-answer-crawler-report',
  '--geo-answer-crawler-matches-csv',
  '--geo-robots-txt',
  '--geo-robots-baseline-txt',
  '--geo-robots-sitemap',
  '--geo-summary-output',
  '--baseline',
  '-c',
  '--config',
];

function bashCompletion(categories: string[]): string {
  return [
    '_aviary_completion() {',
    '  local current previous',
    '  COMPREPLY=()',
    '  current="${COMP_WORDS[COMP_CWORD]}"',
    '  previous="${COMP_WORDS[COMP_CWORD-1]}"',
    '  case "$previous" in',
    '    --preset) COMPREPLY=( $(compgen -W "basic advanced strict geo" -- "$current") ); return ;;',
    '    --wait-until) COMPREPLY=( $(compgen -W "domcontentloaded load networkidle" -- "$current") ); return ;;',
    `    --category) COMPREPLY=( $(compgen -W "${categories.join(' ')}" -- "$current") ); return ;;`,
    '    --completion) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$current") ); return ;;',
    '    --crawl) return ;;',
    `    ${FILE_OPTIONS.join('|')}) compopt -o default; return ;;`,
    '    --max-urls|--max-depth|--max-crawl-page-bytes|--max-crawl-bytes|--concurrency|--watch|--timeout|--settle-ms|--fail-below-score|--fail-on-geo-change-signal|--fail-on-geo-change-url|--fail-on-geo-change-transition|--fail-on-geo-crawler-path-family-failure-rise|--fail-on-geo-answer-owned-citation-drop|--fail-on-geo-answer-provider-balanced-citation-drop|--fail-on-geo-answer-owned-prompt-coverage-drop|--fail-on-geo-answer-owned-top-three-drop|--fail-on-geo-answer-owned-first-position-drop|--fail-on-geo-answer-length-owned-top-three-drop|--fail-on-geo-answer-length-owned-top-three-drop-lower-ci|--fail-on-geo-answer-length-owned-first-position-drop|--fail-on-geo-answer-length-owned-first-position-drop-lower-ci|--fail-on-geo-answer-length-owned-rank-min-matched-prompts|--fail-on-geo-answer-cohort-owned-prompt-coverage-drop|--fail-on-geo-answer-cohort-owned-mrr-drop|--fail-on-geo-answer-cohort-owned-mrr-min-prompts|--fail-on-geo-answer-cohort-monthly-owned-mrr-drop|--fail-on-geo-answer-cohort-monthly-owned-mrr-min-prompts|--fail-on-geo-answer-cohort-monthly-paired-mrr-drop|--fail-on-geo-answer-cohort-monthly-paired-mrr-drop-lower-ci|--fail-on-geo-answer-cohort-monthly-paired-mrr-min-matched-prompts|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop-lower-ci|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-decline|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-alpha|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-min-matched-prompts|--fail-on-geo-answer-cohort-standardized-citation-drop|--fail-on-geo-answer-cohort-standardized-owned-prompt-coverage-drop|--fail-on-geo-answer-entity-mention-drop|--fail-on-geo-answer-entity-owned-top-three-drop|--fail-on-geo-answer-entity-prompt-mention-drop|--fail-on-geo-answer-entity-prompt-balanced-mention-drop|--fail-on-geo-answer-entity-prompt-min-matched-prompts|--fail-on-geo-answer-provider-prompt-overlap-below|--fail-on-geo-answer-provider-min-prompts|--fail-on-geo-answer-provider-min-matched-prompts|--geo-crawler-token|--geo-crawler-path-depth|--geo-ai-referral-source|--geo-answer-path-depth|--geo-answer-entity|--geo-answer-crawler-origin|--geo-crawler-origin|--geo-crawler-sitemap-max-urls|--geo-robots-origin|--geo-robots-token|--geo-path-depth|--geo-sitemap-max-urls|--geo-answer-prompt-plan-min-prompts|--geo-answer-prompt-plan-owned-reach-margin|--geo-answer-prompt-plan-min-jaccard|--geo-answer-prompt-similarity-threshold|--geo-answer-prompt-plan-max-paired-groups) return ;;',
    '  esac',
    `  COMPREPLY=( $(compgen -W "${FLAGS.join(' ')}" -- "$current") )`,
    '}',
    'complete -F _aviary_completion aviary',
    '',
  ].join('\n');
}

function zshCompletion(categories: string[]): string {
  return [
    '#compdef aviary',
    '_aviary() {',
    `  local -a flags categories`,
    `  flags=(${FLAGS.join(' ')})`,
    `  categories=(${categories.join(' ')})`,
    '  case "$words[CURRENT-1]" in',
    '    --preset) compadd -- basic advanced strict geo; return ;;',
    '    --wait-until) compadd -- domcontentloaded load networkidle; return ;;',
    '    --category) compadd -- $categories; return ;;',
    '    --completion) compadd -- bash zsh fish; return ;;',
    '    --crawl) return ;;',
    '    --max-urls|--max-depth|--max-crawl-page-bytes|--max-crawl-bytes|--concurrency|--watch|--timeout|--settle-ms|--fail-below-score|--fail-on-geo-change-signal|--fail-on-geo-change-url|--fail-on-geo-change-transition|--fail-on-geo-crawler-path-family-failure-rise|--fail-on-geo-answer-provider-balanced-citation-drop|--fail-on-geo-answer-owned-prompt-coverage-drop|--fail-on-geo-answer-owned-top-three-drop|--fail-on-geo-answer-owned-first-position-drop|--fail-on-geo-answer-length-owned-top-three-drop|--fail-on-geo-answer-length-owned-top-three-drop-lower-ci|--fail-on-geo-answer-length-owned-first-position-drop|--fail-on-geo-answer-length-owned-first-position-drop-lower-ci|--fail-on-geo-answer-length-owned-rank-min-matched-prompts|--fail-on-geo-answer-cohort-owned-prompt-coverage-drop|--fail-on-geo-answer-cohort-owned-mrr-drop|--fail-on-geo-answer-cohort-owned-mrr-min-prompts|--fail-on-geo-answer-cohort-monthly-owned-mrr-drop|--fail-on-geo-answer-cohort-monthly-owned-mrr-min-prompts|--fail-on-geo-answer-cohort-monthly-paired-mrr-drop|--fail-on-geo-answer-cohort-monthly-paired-mrr-drop-lower-ci|--fail-on-geo-answer-cohort-monthly-paired-mrr-min-matched-prompts|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop-lower-ci|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-decline|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-alpha|--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-min-matched-prompts|--fail-on-geo-answer-cohort-standardized-citation-drop|--fail-on-geo-answer-cohort-standardized-owned-prompt-coverage-drop|--fail-on-geo-answer-entity-mention-drop|--fail-on-geo-answer-entity-owned-top-three-drop|--fail-on-geo-answer-entity-prompt-mention-drop|--fail-on-geo-answer-entity-prompt-balanced-mention-drop|--fail-on-geo-answer-entity-prompt-min-matched-prompts|--fail-on-geo-answer-provider-prompt-overlap-below|--fail-on-geo-answer-provider-min-prompts|--fail-on-geo-answer-provider-min-matched-prompts|--geo-crawler-token|--geo-crawler-path-depth|--geo-ai-referral-source|--geo-answer-path-depth|--geo-answer-entity|--geo-answer-crawler-origin|--geo-crawler-origin|--geo-crawler-sitemap-max-urls|--geo-robots-origin|--geo-robots-token|--geo-path-depth|--geo-sitemap-max-urls|--geo-answer-prompt-plan-min-prompts|--geo-answer-prompt-plan-owned-reach-margin|--geo-answer-prompt-plan-min-jaccard|--geo-answer-prompt-similarity-threshold|--geo-answer-prompt-plan-max-paired-groups) return ;;',
    `    ${FILE_OPTIONS.join('|')}) _files; return ;;`,
    '  esac',
    '  compadd -- $flags',
    '}',
    'compdef _aviary aviary',
    '',
  ].join('\n');
}

function fishCompletion(categories: string[]): string {
  const lines = [
    'complete -c aviary -f -s u -l url -r -d "Target website URL"',
    'complete -c aviary -l urls -r -d "URL list file or glob"',
    'complete -c aviary -f -l sitemap -r -d "Sitemap URL"',
    'complete -c aviary -f -l crawl -r -d "Starting page URL"',
    'complete -c aviary -s o -l output -r -d "JSON report file"',
    'complete -c aviary -l comparison-output -r -d "Baseline comparison JSON file"',
    'complete -c aviary -l fail-on-geo-change-signal -r -d "Exact GEO signal label; requires --fail-on-geo-change"',
    'complete -c aviary -l fail-on-geo-change-url -r -d "Exact changed-page URL; requires --fail-on-geo-change"',
    'complete -c aviary -l fail-on-geo-change-transition -r -d "Exact before-to-after state transition; requires --fail-on-geo-change"',
    'complete -c aviary -l geo-summary-output -r -d "Sitewide GEO summary JSON file"',
    'complete -c aviary -l render -r -d "Saved JSON report"',
    'complete -c aviary -l html -r -d "HTML report file"',
    'complete -c aviary -l pdf -r -d "PDF report file"',
    'complete -c aviary -l history -r -d "JSONL history file"',
    'complete -c aviary -l history-report -r -d "JSONL history file"',
    'complete -c aviary -l junit -r -d "JUnit report file"',
    'complete -c aviary -l sarif -r -d "SARIF issue report file"',
    'complete -c aviary -l markdown -r -d "Markdown report file"',
    'complete -c aviary -l csv -r -d "CSV report file"',
    'complete -c aviary -l bing-ai-csv -r -d "Bing AI Performance CSV export"',
    'complete -c aviary -l bing-ai-xlsx -r -d "Bing AI Performance XLSX workbook"',
    'complete -c aviary -l bing-ai-baseline-csv -r -d "Previous Bing page-citations export"',
    'complete -c aviary -l bing-ai-baseline-xlsx -r -d "Previous Bing page-citations XLSX table"',
    'complete -c aviary -l bing-ai-query-baseline-csv -r -d "Previous Bing query-page mapping export"',
    'complete -c aviary -l bing-ai-query-baseline-xlsx -r -d "Previous Bing query-page XLSX table"',
    'complete -c aviary -l bing-ai-topic-baseline-csv -r -d "Previous Bing topic/intent cohort export"',
    'complete -c aviary -l bing-ai-topic-baseline-xlsx -r -d "Previous Bing topic/intent XLSX table"',
    'complete -c aviary -l google-ai-csv -r -d "Google Search Console generative AI CSV export"',
    'complete -c aviary -l google-ai-xlsx -r -d "Google Search Console generative AI XLSX workbook"',
    'complete -c aviary -l google-ai-discover-csv -r -d "Google Discover generative AI CSV export"',
    'complete -c aviary -l google-ai-discover-xlsx -r -d "Google Discover generative AI XLSX workbook"',
    'complete -c aviary -l google-ai-baseline-csv -r -d "Previous Google Search or Discover page export"',
    'complete -c aviary -l google-ai-baseline-xlsx -r -d "Previous Google Search or Discover page table in XLSX"',
    'complete -c aviary -l google-ai-dimension-baseline-csv -r -d "Previous Google Search or Discover export with matching dimensions"',
    'complete -c aviary -l google-ai-dimension-baseline-xlsx -r -d "Previous Google Search or Discover XLSX table with matching dimensions"',
    'complete -c aviary -f -l geo-platform-matrix -d "Join Google Search and Bing page observations"',
    'complete -c aviary -f -l geo-google-surface-matrix -d "Join Google Search and Discover page observations"',
    'complete -c aviary -l geo-google-surface-baseline-json -r -d "Previous Google Search/Discover matrix JSON"',
    'complete -c aviary -l geo-google-surface-path-family-csv -r -d "Google Search/Discover path-family CSV report"',
    'complete -c aviary -l geo-platform-baseline-json -r -d "Previous GEO platform matrix JSON"',
    'complete -c aviary -f -l geo-sitemap -r -d "Same-origin sitemap or index for matrix membership"',
    'complete -c aviary -f -l geo-sitemap-max-urls -r -d "Maximum sitemap URLs to inspect, from 1 to 10000"',
    'complete -c aviary -f -l geo-path-depth -r -d "Path prefix depth for matrix families, from 1 to 5"',
    'complete -c aviary -l geo-audit-json -r -d "Aviary audit or GEO summary JSON for correlation"',
    'complete -c aviary -l geo-audit-baseline-json -r -d "Prior audit snapshot for owned-page/provider GEO period comparisons"',
    'complete -c aviary -l geo-crawler-log -r -d "Local Apache/Nginx, CloudFront, or JSONL crawler log, including Cloudflare fields"',
    'complete -c aviary -l geo-crawler-token -f -r -d "Custom user-agent token (activity remains unclassified)"',
    'complete -c aviary -l geo-crawler-ip-ranges -r -d "Offline JSON CIDR list for optional crawler source-IP verification"',
    'complete -c aviary -l geo-ai-referral-source -f -r -d "Label an exact UTM source value in access-log reports"',
    'complete -c aviary -l geo-answer-observations -r -d "JSON file of locally recorded AI answer prompts and cited URLs"',
    'complete -c aviary -l geo-answer-baseline-observations -r -d "Previous manual AI answer sample for matched prompt/provider comparison"',
    'complete -c aviary -l geo-answer-source-portfolio-attribution-csv -r -d "Attribute matched-prompt citation-share changes to source domains"',
    'complete -c aviary -l geo-answer-source-portfolio-attribution-json -r -d "Structured source-domain attribution rows and uncertainty metadata"',
    'complete -c aviary -l geo-answer-source-portfolio-attribution-html -r -d "Offline provider/source share-movement dashboard"',
    'complete -c aviary -l geo-answer-owned-source-share-gate-csv -r -d "Save owned source-share gate assessment CSV"',
    'complete -c aviary -l geo-answer-owned-source-share-gate-json -r -d "Structured owned source-share gate assessment JSON"',
    'complete -c aviary -l geo-answer-provider-source-network-edge-drift-csv -r -d "Compare baseline/current provider edge-gap changes"',
    'complete -c aviary -l geo-answer-provider-source-network-edge-drift-html -r -d "Offline provider edge-drift review page"',
    'complete -c aviary -l geo-answer-comparison-csv -r -d "Spreadsheet-safe matched prompt/provider comparison CSV"',
    'complete -c aviary -l geo-answer-cohort-standardization-csv -r -d "Provider citation coverage standardized to a shared topic/intent mix"',
    'complete -c aviary -l geo-answer-cohort-period-standardization-csv -r -d "Provider baseline/current coverage standardized to a shared cohort mix"',
    'complete -c aviary -l geo-answer-prompt-sampling-plan-csv -r -d "Plan additional unique prompts to balance provider cohort samples"',
    'complete -c aviary -l geo-answer-prompt-sampling-plan-json -r -d "Typed JSON prompt-panel plan with target and budget summaries"',
    'complete -c aviary -l geo-answer-prompt-plan-provider-pairs-csv -r -d "One budget summary row per provider pair"',
    'complete -c aviary -l geo-answer-execution-context-csv -r -d "Citation coverage by operator-recorded model, surface, locale, and topic/intent"',
    'complete -c aviary -l geo-answer-execution-context-comparison-csv -r -d "Compare execution-context coverage across baseline/current samples"',
    'complete -c aviary -l geo-answer-execution-context-trends-csv -r -d "Export monthly execution-context citation coverage and trends"',
    'complete -c aviary -l geo-answer-length-profiles-csv -r -d "Export prompt-balanced citation density and owned rank by answer word-count band"',
    'complete -c aviary -l geo-answer-length-comparison-csv -r -d "Compare matched-prompt owned-rank changes and separate within-band from answer-length-mix effects"',
    'complete -c aviary -l geo-answer-length-trends-csv -r -d "Export pooled and prompt-equal citation-density trends by UTC month"',
    'complete -c aviary -l geo-answer-prompt-plan-min-prompts -r -d "Minimum unique prompts per provider/cohort quota, 1 to 10000"',
    'complete -c aviary -l geo-answer-prompt-plan-owned-reach-margin -r -d "Worst-case 95% Wilson half-width target in percentage points, 0.5 to 50"',
    'complete -c aviary -l geo-answer-prompt-plan-min-jaccard -r -d "Minimum exact-prompt Jaccard target per provider/cohort, 0.5 to 0.99"',
    'complete -c aviary -l geo-answer-prompt-plan-max-paired-groups -r -d "Maximum new paired prompt groups per provider pair; distribute across cohorts"',
    'complete -c aviary -l geo-answer-prompt-plan-max-total-paired-groups -r -d "Maximum new paired prompt groups across all provider pairs"',
    'complete -c aviary -l geo-answer-prompt-plan-total-allocation -r -a "balanced proportional" -d "Split a total capture budget evenly or by required provider-pair demand"',
    'complete -c aviary -l geo-answer-prompt-plan-cohort-targets -r -d "Per-cohort quota floors and paired-group ceilings from a JSON file"',
    'complete -c aviary -f -l fail-on-geo-answer-prompt-plan-miss -d "Fail when GEO prompt-plan quotas, requested targets, or retained detail are incomplete"',
    'complete -c aviary -l geo-answer-prompt-families-csv -r -d "Lexical prompt-family reach and source evidence CSV"',
    'complete -c aviary -l geo-answer-prompt-families-html -r -d "Compare pooled prompt and equal-family weighting"',
    'complete -c aviary -l geo-answer-prompt-family-influence-csv -r -d "Rank families by leave-one-out source concentration influence"',
    'complete -c aviary -l geo-answer-prompt-family-influence-html -r -d "Plot leave-one-family-out GEO metric shifts"',
    'complete -c aviary -l geo-answer-prompt-family-threshold-sweep-csv -r -d "Prompt-family clustering and reach sensitivity across cosine cutoffs"',
    'complete -c aviary -l geo-answer-prompt-family-threshold-sweep-html -r -d "Offline prompt-family topology and provider-reach dashboard"',
    'complete -c aviary -l geo-answer-execution-context-csv -r -d "Citation coverage by recorded model, surface, locale, and topic/intent"',
    'complete -c aviary -l geo-answer-execution-context-coverage-csv -r -d "Model, surface, and locale label coverage by provider/cohort and month"',
    'complete -c aviary -l geo-answer-execution-context-comparison-csv -r -d "Execution-context citation coverage across baseline/current samples"',
    'complete -c aviary -l geo-answer-execution-context-trends-csv -r -d "Monthly execution-context citation coverage trends"',
    'complete -c aviary -l geo-answer-provider-position-comparison-csv -r -d "Spreadsheet-safe provider-specific cited-page source-position comparison CSV"',
    'complete -c aviary -l geo-answer-cohorts-csv -r -d "Spreadsheet-safe current topic/intent/provider cohort CSV"',
    'complete -c aviary -l geo-answer-cohort-comparison-csv -r -d "Spreadsheet-safe matched and one-period-only cohort comparison CSV"',
    'complete -c aviary -l geo-answer-provider-pairs-csv -r -d "Shared-prompt owned-reach test with sensitivity and Holm adjustment"',
    'complete -c aviary -l geo-answer-owned-prompt-reach-period-csv -r -d "Matched-period owned reach with sensitivity and Holm-adjusted exact test"',
    'complete -c aviary -l geo-answer-sample-mix-csv -r -d "Spreadsheet-safe provider topic/intent sample mix comparison CSV"',
    'complete -c aviary -l geo-answer-stability-csv -r -d "Spreadsheet-safe repeated-prompt citation source stability CSV"',
    'complete -c aviary -l geo-answer-source-persistence-csv -r -d "Next-timestamp citation-domain persistence CSV"',
    'complete -c aviary -l geo-answer-cohort-trends-csv -r -d "Spreadsheet-safe monthly provider/topic/intent coverage and owned-rank trend CSV"',
    'complete -c aviary -l geo-answer-audit-signals-csv -r -d "Spreadsheet-safe GEO audit signal breakdown for cited pages"',
    'complete -c aviary -l geo-answer-audited-owned-page-provider-inventory-csv -r -d "Owned audited-page by provider citation and crawler-state inventory"',
    'complete -c aviary -l geo-answer-audited-owned-page-provider-inventory-html -r -d "Offline owned-page by provider citation and crawler-state dashboard"',
    'complete -c aviary -l geo-answer-audited-owned-page-provider-inventory-comparison-csv -r -d "Compare audited page/provider citation states across answer samples"',
    'complete -c aviary -l geo-answer-audited-owned-page-provider-inventory-comparison-html -r -d "Offline audited page/provider period review dashboard"',
    'complete -c aviary -l geo-answer-audited-owned-page-provider-inventory-comparison-json -r -d "Typed audited page/provider period evidence JSON"',
    'complete -c aviary -l geo-answer-audited-owned-pages-csv -r -d "Spreadsheet-safe owned audited-page citation inventory"',
    'complete -c aviary -l geo-answer-audited-owned-page-comparison-csv -r -d "Spreadsheet-safe baseline/current owned audited-page citation comparison"',
    'complete -c aviary -l geo-answer-audited-owned-page-providers-csv -r -d "Spreadsheet-safe owned audited-page citation detail by provider"',
    'complete -c aviary -l geo-answer-audited-owned-page-provider-comparison-csv -r -d "Spreadsheet-safe provider-level owned-page rank comparison"',
    'complete -c aviary -l geo-answer-source-category -f -r -d "Hostname=category mapping for observed citations; repeatable"',
    'complete -c aviary -l geo-answer-source-categories-csv -r -d "Spreadsheet-safe category, provider, and citation-rank distribution"',
    'complete -c aviary -l geo-answer-source-category-comparison-csv -r -d "Spreadsheet-safe baseline/current category and rank comparison"',
    'complete -c aviary -l geo-answer-source-category-prompt-coverage-csv -r -d "Spreadsheet-safe exact-prompt source-category coverage by provider"',
    'complete -c aviary -l geo-answer-source-category-prompt-details-csv -r -d "Spreadsheet-safe source-category prompt and provider evidence rows"',
    'complete -c aviary -l geo-answer-source-category-trends-csv -r -d "Spreadsheet-safe monthly source-category presence by provider/cohort"',
    'complete -c aviary -l geo-answer-source-category-provider-pairs-csv -r -d "Spreadsheet-safe shared-prompt source-category coverage by provider pair"',
    'complete -c aviary -l geo-answer-source-category-cooccurrence-csv -r -d "Spreadsheet-safe source-category co-citation by provider"',
    'complete -c aviary -l geo-answer-source-category-path-families-csv -r -d "Source-category path families by provider; requires mapping and path depth"',
    'complete -c aviary -l geo-answer-source-category-monthly-gates-json -r -d "Save enabled monthly source-category gate assessments as versioned JSON"',
    'complete -c aviary -l geo-answer-source-category-path-family-comparison-csv -r -d "Baseline/current source-category path-family comparison"',
    'complete -c aviary -l geo-answer-citation-positions-csv -r -d "Spreadsheet-safe source-list position summaries for cited pages and domains"',
    'complete -c aviary -l geo-answer-citation-date-alignment-csv -r -d "Schema dateModified vs last captured citation day"',
    'complete -c aviary -l geo-answer-owned-rank-csv -r -d "Owned citation rank buckets and first-owned-citation mean reciprocal rank"',
    'complete -c aviary -l geo-answer-owned-rank-comparison-csv -r -d "Spreadsheet-safe baseline/current owned citation rank comparison"',
    'complete -c aviary -l geo-answer-owned-prompt-rank-comparison-csv -r -d "Exact-prompt-balanced owned rank comparison with paired-prompt confidence intervals"',
    'complete -c aviary -l geo-answer-co-citation-csv -r -d "Spreadsheet-safe external-domain co-citations with owned sources"',
    'complete -c aviary -l geo-answer-co-citation-comparison-csv -r -d "Spreadsheet-safe baseline/current co-citation comparison"',
    'complete -c aviary -l geo-answer-entity -f -r -d "Entity name with optional pipe-separated exact aliases; repeatable"',
    'complete -c aviary -l geo-answer-entity-mentions-csv -r -d "Spreadsheet-safe answer entity mention and citation coverage CSV"',
    'complete -c aviary -l geo-answer-entity-prompt-details-csv -r -d "Exact-prompt entity mention, citation coverage, and owned placement CSV"',
    'complete -c aviary -l geo-answer-entity-prompt-provider-pairs-csv -r -d "Entity outcomes compared across providers on shared exact prompts"',
    'complete -c aviary -l geo-answer-entity-prompt-comparison-csv -r -d "Baseline/current matched exact-prompt entity outcomes CSV"',
    'complete -c aviary -l geo-answer-entity-co-mentions-csv -r -d "Spreadsheet-safe entity co-mentions, confidence intervals, and monthly cohorts"',
    'complete -c aviary -l geo-answer-entity-co-mention-comparison-csv -r -d "Spreadsheet-safe baseline/current entity co-mention comparison"',
    'complete -c aviary -l geo-answer-entity-citation-domains-csv -r -d "Spreadsheet-safe citation-domain shares by exact entity mention"',
    'complete -c aviary -l geo-answer-entity-citation-pages-csv -r -d "Exact cited-page coverage by entity mention, provider, cohort, and UTC month"',
    'complete -c aviary -l geo-answer-entity-source-categories-csv -r -d "Spreadsheet-safe entity-conditioned source-category citation shares"',
    'complete -c aviary -l geo-answer-entity-source-category-comparison-csv -r -d "Spreadsheet-safe baseline/current entity source-category comparison"',
    'complete -c aviary -l geo-answer-entity-citation-domain-comparison-csv -r -d "Spreadsheet-safe baseline/current entity citation-domain comparison"',
    'complete -c aviary -l geo-answer-entity-citation-page-comparison-csv -r -d "Baseline/current exact cited-page comparison by entity mention"',
    'complete -c aviary -l geo-answer-entity-citation-position-comparison-csv -r -d "Spreadsheet-safe baseline/current owned citation ranks conditioned on exact entity mentions"',
    'complete -c aviary -l geo-answer-entity-opportunities-csv -r -d "Spreadsheet-safe mentioned-entity without-owned-citation review CSV"',
    'complete -c aviary -l geo-answer-entity-prompt-matched-association-csv -r -d "Prompt-matched entity-mention vs owned-citation association CSV"',
    'complete -c aviary -l geo-answer-entity-prompt-matched-association-html -r -d "Filterable offline prompt-matched entity/citation dashboard"',
    'complete -c aviary -l geo-answer-entity-path-families-csv -r -d "Entity-conditioned cited URL path-family coverage CSV"',
    'complete -c aviary -l geo-answer-entity-path-family-monthly-csv -r -d "UTC-month entity-conditioned path-family profiles"',
    'complete -c aviary -l geo-answer-entity-path-family-comparison-csv -r -d "Baseline/current entity-conditioned path-family comparison CSV"',
    'complete -c aviary -f -l geo-answer-path-depth -r -d "Group captured citation URLs by the first 1 to 5 path segments"',
    'complete -c aviary -l geo-answer-path-family-csv -r -d "Spreadsheet-safe answer citation path-family CSV"',
    'complete -c aviary -l geo-answer-path-family-cohorts-csv -r -d "Cited path-family coverage by provider and topic/intent"',
    'complete -c aviary -l geo-answer-path-family-trends-csv -r -d "Monthly cited path-family coverage by provider/cohort"',
    'complete -c aviary -l fail-on-geo-answer-path-family-coverage-drop -r -d "Fail on a matched path-family cohort coverage decline"',
    'complete -c aviary -l fail-on-geo-answer-path-family-prompt-coverage-drop -r -d "Fail on a distinct-prompt path-family coverage decline"',
    'complete -c aviary -l fail-on-geo-answer-path-family-over-index-drop -r -d "Fail on a relative decline in path-family cohort over-index"',
    'complete -c aviary -l fail-on-geo-answer-entity-path-family-prompt-coverage-drop -r -d "Fail on entity-mentioned path-family prompt coverage declines"',
    'complete -c aviary -l fail-on-geo-answer-entity-path-family-top-three-drop -r -d "Fail on entity-mentioned path-family top-three placement declines"',
    'complete -c aviary -l fail-on-geo-answer-entity-citation-page-prompt-coverage-drop -r -d "Fail on entity-mentioned exact-page prompt coverage declines"',
    'complete -c aviary -l fail-on-geo-answer-entity-citation-page-top-three-drop -r -d "Fail on entity-mentioned exact-page top-three placement declines"',
    'complete -c aviary -l fail-on-geo-answer-entity-prompt-mention-drop -r -d "Fail on pooled entity mention-rate declines across shared exact prompts"',
    'complete -c aviary -l fail-on-geo-answer-entity-prompt-balanced-mention-drop -r -d "Fail on equal-prompt/provider mean entity mention-rate declines"',
    'complete -c aviary -l fail-on-geo-answer-provider-balanced-citation-drop -r -d "Fail on equal-prompt mean citation coverage declines by provider"',
    'complete -c aviary -l fail-on-geo-answer-owned-prompt-coverage-drop -r -d "Fail on owned citation reach declines across matched prompts"',
    'complete -c aviary -l fail-on-geo-answer-owned-reach-bound-drop -r -d "Fail only on declines beyond the optimistic completeness bound"',
    'complete -c aviary -l fail-on-geo-answer-cohort-owned-prompt-coverage-drop -r -d "Fail on owned-cited prompt-reach declines within matched cohorts"',
    'complete -c aviary -l fail-on-geo-answer-cohort-owned-mrr-drop -r -d "Fail on first-owned-citation MRR declines within matched cohorts"',
    'complete -c aviary -l fail-on-geo-answer-cohort-owned-mrr-min-prompts -r -d "Require owned-cited prompt support per period/cohort for the MRR gate"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-mrr-drop -r -d "Fail on latest sampled-month cohort MRR declines"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-mrr-min-prompts -r -d "Require owned-cited prompt support in each sampled month"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-paired-mrr-drop -r -d "Fail on paired-prompt monthly MRR declines"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-paired-mrr-drop-lower-ci -r -d "Fail when a paired bootstrap interval confirms an MRR decline"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-paired-mrr-min-matched-prompts -r -d "Require shared owned-cited prompt support per monthly transition"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop -r -d "Fail on paired monthly owned-citing prompt reach declines"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop-lower-ci -r -d "Fail when a paired bootstrap interval confirms reach decline"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-decline -r -d "Fail on Holm-adjusted paired reach declines"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-alpha -r -d "Set Holm-adjusted p-value cutoff"',
    'complete -c aviary -l fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-min-matched-prompts -r -d "Require shared prompt support for monthly owned reach"',
    'complete -c aviary -l fail-on-geo-answer-entity-prompt-min-matched-prompts -r -d "Require minimum distinct matched prompts per entity"',
    'complete -c aviary -l fail-on-geo-answer-provider-prompt-overlap-below -r -d "Require provider prompt-panel Jaccard overlap"',
    'complete -c aviary -l fail-on-geo-answer-provider-min-prompts -r -d "Require minimum distinct prompt support per provider"',
    'complete -c aviary -l fail-on-geo-answer-provider-min-matched-prompts -r -d "Require minimum shared prompt support per provider across periods"',
    'complete -c aviary -l geo-answer-provider-prompt-overlap-csv -r -d "Export provider prompt-panel overlap CSV"',
    'complete -c aviary -l geo-answer-provider-prompt-source-overlap-csv -r -d "Export same-prompt provider citation-domain overlap CSV"',
    'complete -c aviary -l fail-on-geo-answer-sample-mix-divergence -r -d "Fail when provider topic/intent sample mixes diverge"',
    'complete -c aviary -l fail-on-geo-answer-cohort-standardized-citation-drop -r -d "Fail on provider citation-coverage drops after cohort adjustment"',
    'complete -c aviary -l fail-on-geo-answer-cohort-standardized-owned-prompt-coverage-drop -r -d "Fail on owned-cited prompt reach drops after cohort adjustment"',
    'complete -c aviary -l geo-answer-path-family-cohort-comparison-csv -r -d "Compare path-family cohort coverage across answer samples"',
    'complete -c aviary -l geo-answer-path-family-comparison-csv -r -d "Spreadsheet-safe baseline/current citation path-family comparison CSV"',
    'complete -c aviary -l geo-answer-crawler-report -r -d "Prior AI crawler access-log report for cited-path correlation"',
    'complete -c aviary -l geo-answer-crawler-origin -f -r -d "Exact site origin for cited-path crawler-log correlation"',
    'complete -c aviary -l geo-answer-crawler-matches-csv -r -d "Spreadsheet-safe cited-page and crawler-path matches CSV"',
    'complete -c aviary -l geo-answer-domain-prompt-coverage-csv -r -d "Distinct-prompt domain citation reach"',
    'complete -c aviary -l geo-answer-source-rarefaction-csv -r -d "Domain/category discovery, retained-catalog sample targets, marginal yield, and completeness exposure"',
    'complete -c aviary -l geo-answer-prompt-family-source-rarefaction-csv -r -d "Source discovery rarefaction using lexical prompt families"',
    'complete -c aviary -l geo-answer-prompt-family-source-rarefaction-html -r -d "Family-weighted source-discovery chart report"',
    'complete -c aviary -l geo-answer-prompt-family-source-rarefaction-sweep-csv -r -d "Family-weighted source discovery across lexical thresholds"',
    'complete -c aviary -l geo-answer-prompt-family-source-rarefaction-sweep-html -r -d "Offline family-weighted source discovery dashboard across thresholds"',
    'complete -c aviary -l geo-answer-provider-prompt-family-source-overlap-csv -r -d "Compare provider sources within lexical prompt families"',
    'complete -c aviary -l geo-answer-provider-prompt-family-source-overlap-html -r -d "Offline provider source-overlap dashboard by prompt family"',
    'complete -c aviary -l geo-answer-provider-prompt-family-source-overlap-sweep-csv -r -d "Compare family source overlap across lexical thresholds"',
    'complete -c aviary -l geo-answer-provider-prompt-family-source-overlap-sweep-html -r -d "Offline provider source-divergence sensitivity dashboard"',
    'complete -c aviary -l geo-answer-prompt-family-period-comparison-csv -r -d "Compare provider sources across baseline/current lexical families"',
    'complete -c aviary -l geo-answer-prompt-family-period-comparison-html -r -d "Offline family source-change dashboard"',
    'complete -c aviary -l geo-answer-prompt-family-period-comparison-sweep-csv -r -d "Compare family source turnover across lexical thresholds"',
    'complete -c aviary -l geo-answer-prompt-family-period-comparison-sweep-summary-csv -r -d "Export family-balanced divergence means and intervals"',
    'complete -c aviary -l geo-answer-prompt-family-period-comparison-sweep-html -r -d "Offline longitudinal family-source sensitivity dashboard"',
    'complete -c aviary -l geo-answer-source-rarefaction-batch-size -r -d "Prompts in each marginal rarefaction batch (1–1,000)"',
    'complete -c aviary -l geo-answer-domain-prompt-coverage-comparison-csv -r -d "Compare domain prompt reach by provider"',
    'complete -c aviary -l fail-on-geo-answer-source-category-monthly-top-three-hhi-rise-above -r -d "Fail when top-three category HHI rises between sampled months"',
    'complete -c aviary -l fail-on-geo-answer-source-category-monthly-top-three-hhi-above -r -d "Fail when top-three mapped category HHI exceeds its monthly ceiling"',
    'complete -c aviary -l geo-answer-domain-paired-reach-comparison-csv -r -d "Compare domain citation reach on matched prompts across samples"',
    'complete -c aviary -l fail-on-geo-answer-domain-paired-reach-drop -r -d "Fail on statistically significant paired-prompt domain reach loss"',
    'complete -c aviary -l fail-on-geo-answer-domain-paired-reach-alpha -r -d "Adjusted significance threshold for the paired-reach gate"',
    'complete -c aviary -l fail-on-geo-answer-domain-paired-reach-min-prompts -r -d "Minimum matched-prompt support for the paired-reach gate"',
    'complete -c aviary -l geo-answer-domain-paired-reach-gate-json -r -d "Save versioned paired domain-reach gate assessment JSON"',
    'complete -c aviary -l geo-answer-page-paired-reach-comparison-csv -r -d "Compare exact-page citation reach on matched prompts"',
    'complete -c aviary -l geo-answer-page-opportunities-csv -r -d "Exact third-party pages cited when owned citation absence is confirmed"',
    'complete -c aviary -l geo-answer-page-opportunity-trends-csv -r -d "Track confirmed-no-owned exact-page opportunities by UTC month"',
    'complete -c aviary -l geo-answer-page-opportunity-path-families-csv -r -d "Aggregate confirmed-no-owned pages into URL path families"',
    'complete -c aviary -l geo-answer-page-opportunity-path-family-depth-sweep-csv -r -d "Compare opportunity family consolidation across URL path depths"',
    'complete -c aviary -l geo-answer-page-opportunity-path-family-depth-sweep-html -r -d "Render a chart and filterable URL path-depth sensitivity dashboard"',
    'complete -c aviary -l geo-answer-page-opportunity-path-family-trends-csv -r -d "Track confirmed-no-owned path-family reach by UTC month with paired prompt transitions"',
    'complete -c aviary -l geo-answer-page-opportunity-path-family-trends-html -r -d "Render a filterable monthly page-opportunity path-family dashboard"',
    'complete -c aviary -l fail-on-geo-answer-page-opportunity-path-family-monthly-rise -r -d "Fail on Holm-significant monthly page-opportunity path-family reach gains"',
    'complete -c aviary -l fail-on-geo-answer-page-opportunity-path-family-monthly-alpha -r -d "Adjusted p-value ceiling for the monthly path-family rise gate"',
    'complete -c aviary -l fail-on-geo-answer-page-opportunity-path-family-monthly-min-prompts -r -d "Minimum matched prompts for monthly path-family rise gate"',
    'complete -c aviary -l geo-answer-page-opportunity-path-family-monthly-gate-json -r -d "Save versioned monthly path-family rise gate JSON"',
    'complete -c aviary -l geo-answer-page-opportunity-path-depth -r -d "Leading path segments for page opportunity families (1–5)"',
    'complete -c aviary -l fail-on-geo-answer-page-opportunity-monthly-rise -r -d "Fail on a Holm-significant paired monthly page-reach rise"',
    'complete -c aviary -l fail-on-geo-answer-page-opportunity-monthly-alpha -r -d "Adjusted p-value ceiling for monthly page-opportunity rise gate"',
    'complete -c aviary -l fail-on-geo-answer-page-opportunity-monthly-min-prompts -r -d "Minimum matched prompts for monthly page-opportunity rise gate"',
    'complete -c aviary -l geo-answer-page-opportunity-monthly-gate-json -r -d "Save versioned monthly page-opportunity gate JSON"',
    'complete -c aviary -f -l geo-answer-page-paired-reach-owned-only -d "Limit comparison to configured owned hosts and subdomains"',
    'complete -c aviary -l fail-on-geo-answer-page-paired-reach-drop -r -d "Fail on statistically significant paired-prompt exact-page reach loss"',
    'complete -c aviary -l fail-on-geo-answer-page-paired-reach-alpha -r -d "Adjusted significance threshold for the page paired-reach gate"',
    'complete -c aviary -l fail-on-geo-answer-page-paired-reach-min-prompts -r -d "Minimum matched-prompt support for the page gate"',
    'complete -c aviary -l geo-answer-page-paired-reach-metric -r -a "citation-reach top-three-reach first-position-reach" -d "Endpoint selected for the page reach gate"',
    'complete -c aviary -l geo-answer-page-paired-reach-gate-json -r -d "Save versioned exact-page reach gate assessment JSON"',
    'complete -c aviary -l geo-answer-source-diversity-uncertainty-csv -r -d "Bootstrap event/rank-weighted source concentration and breadth uncertainty"',
    'complete -c aviary -l geo-answer-source-diversity-uncertainty-html -r -d "Offline provider source-concentration interval dashboard"',
    'complete -c aviary -l geo-answer-source-diversity-comparison-csv -r -d "Compare citation source diversity on shared prompts across samples"',
    'complete -c aviary -l geo-answer-source-diversity-comparison-html -r -d "Offline matched-prompt source-diversity change dashboard"',
    'complete -c aviary -l geo-answer-provider-source-divergence-csv -r -d "Compare provider source distributions over shared exact prompts"',
    'complete -c aviary -l geo-answer-source-portfolio-drift-csv -r -d "Compare baseline/current source portfolios over matched provider prompts"',
    'complete -c aviary -l geo-answer-source-network-csv -r -d "Provider citation-source co-occurrence edges and centrality"',
    'complete -c aviary -l geo-answer-source-network-comparison-csv -r -d "Matched-period provider source-network changes"',
    'complete -c aviary -l geo-answer-rank-weighted-source-network-csv -r -d "Rank-weighted source network and centrality"',
    'complete -c aviary -l geo-answer-rank-weighted-source-network-comparison-csv -r -d "Compare matched-period rank-weighted source networks"',
    'complete -c aviary -l geo-answer-source-network-html -r -d "Interactive offline citation-source graph dashboard"',
    'complete -c aviary -l geo-answer-source-network-comparison-html -r -d "Review matched-period community and topology drift"',
    'complete -c aviary -l geo-answer-provider-source-network-overlap-csv -r -d "Compare provider co-citation topology on shared exact prompts"',
    'complete -c aviary -l geo-answer-provider-source-network-edge-comparison-csv -r -d "Compare source-pair support on matched provider prompts"',
    'complete -c aviary -l geo-answer-provider-source-network-edge-html -r -d "Offline provider edge-comparison review table"',
    'complete -c aviary -l geo-answer-owned-source-network-gaps-csv -r -d "Find external source pairs associated with owned-citation gaps"',
    'complete -c aviary -l geo-answer-prompt-similarity-csv -r -d "Screen exact prompts for lexical wording overlap"',
    'complete -c aviary -l geo-answer-prompt-similarity-threshold -r -d "Minimum TF-IDF cosine similarity, from 0 to 1"',
    'complete -c aviary -l geo-answer-prompt-families-csv -r -d "Group exact prompts into lexical similarity components"',
    'complete -c aviary -l geo-answer-prompt-families-html -r -d "Plot prompt-family weighting sensitivity"',
    'complete -c aviary -l geo-answer-prompt-family-influence-csv -r -d "Export leave-one-family-out GEO sensitivity"',
    'complete -c aviary -l geo-answer-prompt-family-influence-html -r -d "Visualize leave-one-family-out GEO sensitivity"',
    'complete -c aviary -l geo-answer-prompt-family-threshold -r -d "Minimum TF-IDF cosine edge for prompt-family components"',
    'complete -c aviary -l geo-answer-owned-prompt-coverage-csv -r -d "Owned citation reach by unique prompt, overall and by provider"',
    'complete -c aviary -l geo-answer-owned-prompt-opportunities-csv -r -d "Exact provider/prompt groups with no owned citation"',
    'complete -c aviary -l geo-answer-competitive-gaps-csv -r -d "Cited alternative domains for owned citation gaps"',
    'complete -c aviary -l geo-answer-provider-owned-gaps-csv -r -d "Exact prompts with owned citation on one provider but not another"',
    'complete -c aviary -l geo-answer-provider-owned-gap-comparison-csv -r -d "Track exact-prompt owned-citation gap states across baseline/current samples"',
    'complete -c aviary -l geo-answer-competitive-gap-comparison-csv -r -d "Compare cited alternatives across owned citation gaps"',
    'complete -c aviary -l geo-answer-owned-domain -f -r -d "Owned hostname, including subdomains, for answer citation coverage"',
    'complete -c aviary -l geo-crawler-origin -f -r -d "Site origin for audit or sitemap crawler-log correlation"',
    'complete -c aviary -l geo-crawler-sitemap -f -r -d "Same-origin sitemap for lastmod versus crawler-log comparison"',
    'complete -c aviary -f -l geo-crawler-sitemap-max-urls -r -d "Sitemap URL limit for crawler date comparison, from 1 to 10000"',
    'complete -c aviary -l geo-robots-txt -r -d "Local robots.txt snapshot for offline crawler path replay"',
    'complete -c aviary -l geo-robots-baseline-txt -r -d "Previous robots.txt snapshot for GEO policy comparison"',
    'complete -c aviary -l geo-robots-origin -f -r -d "Site origin for replay against the robots snapshot"',
    'complete -c aviary -l geo-robots-sitemap -r -d "Same-origin sitemap URL list for robots policy replay"',
    'complete -c aviary -l geo-robots-token -f -r -d "Custom user-agent token for saved-audit or sitemap replay"',
    'complete -c aviary -l baseline -r -d "Baseline report file"',
    'complete -c aviary -s c -l config -r -d "Configuration file"',
    'complete -c aviary -f -l viewport -r -d "Viewport dimensions"',
    'complete -c aviary -f -l max-urls -r -d "Sitemap or crawl URL limit"',
    'complete -c aviary -f -l max-depth -r -d "Maximum link crawl depth"',
    'complete -c aviary -f -l max-crawl-page-bytes -r -d "Maximum HTML bytes per crawled page"',
    'complete -c aviary -f -l max-crawl-bytes -r -d "Maximum combined crawl HTML bytes"',
    'complete -c aviary -f -l concurrency -r -d "Concurrent browser count"',
    'complete -c aviary -f -l watch -r -d "Watch interval in seconds"',
    'complete -c aviary -f -l timeout -r -d "Navigation timeout in milliseconds"',
    'complete -c aviary -f -l settle-ms -r -d "Fixed post-navigation settle delay in milliseconds"',
    'complete -c aviary -f -l wait-until -a "domcontentloaded load networkidle" -d "Navigation readiness condition"',
    'complete -c aviary -f -l fail-below-score -r -d "Minimum score"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-source-share-drop -r -d "Maximum prompt-balanced owned source-share decline, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-source-share-drop-lower-ci -r -d "Fail when the 95% prompt-cluster lower bound for owned-share decline exceeds this threshold"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-source-share-sign-test-alpha -r -d "One-sided exact prompt sign-test alpha with Holm correction across providers"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-source-share-min-prompts -r -d "Minimum matched both-cited prompt support, 2 to 10000 (default 10)"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-citation-drop -r -d "Maximum allowed owned-citation coverage drop, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-reach-bound-drop -r -d "Maximum decline after incomplete-list bounds"',
    'complete -c aviary -f -l fail-on-geo-answer-unknown-owned-observation-share -r -d "Maximum unknown owned-citation observation share"',
    'complete -c aviary -f -l fail-on-geo-answer-unknown-owned-prompt-share -r -d "Maximum unknown owned-citation prompt share"',
    'complete -c aviary -f -l fail-on-geo-answer-unknown-owned-state-share-rise -r -d "Maximum monthly increase in unknown owned-citation state share"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-first-position-drop -r -d "Maximum allowed drop in owned citation-event share at rank 1, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-top-three-drop -r -d "Maximum allowed drop in owned citation-event share at ranks 1 to 3, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-first-position-drop -r -d "Maximum prompt-balanced rank-one share decline, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-first-position-drop-lower-ci -r -d "Minimum paired-prompt rank-one 95% interval drop, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-top-three-drop -r -d "Maximum prompt-balanced top-three share decline, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-top-three-drop-lower-ci -r -d "Minimum paired-prompt top-three 95% interval drop, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-rank-min-matched-prompts -r -d "Minimum paired exact-prompt support for owned-rank gates"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-mrr-drop -r -d "Maximum prompt-balanced mean reciprocal rank drop, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-owned-prompt-balanced-mrr-drop-lower-ci -r -d "Minimum paired-prompt reciprocal-rank 95% interval drop"',
    'complete -c aviary -f -l fail-on-geo-answer-length-owned-top-three-drop -r -d "Maximum paired-prompt owned top-three-share drop"',
    'complete -c aviary -f -l fail-on-geo-answer-length-owned-top-three-drop-lower-ci -r -d "Drop threshold for lower 95% paired-prompt bootstrap bound; defaults to 10 prompts"',
    'complete -c aviary -f -l fail-on-geo-answer-length-owned-first-position-drop -r -d "Maximum paired-prompt owned rank-one-share decline, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-length-owned-first-position-drop-lower-ci -r -d "Rank-one decline threshold for the lower 95% paired-prompt bootstrap bound"',
    'complete -c aviary -f -l fail-on-geo-answer-length-owned-rank-min-matched-prompts -r -d "Minimum exact prompts with owned citations in both periods per matched band; any unsupported band fails the gate"',
    'complete -c aviary -f -l fail-on-geo-answer-entity-mention-drop -r -d "Maximum allowed drop in configured answer-text entity mention rate, in percentage points"',
    'complete -c aviary -f -l fail-on-geo-answer-entity-owned-top-three-drop -r -d "Maximum allowed drop in owned citation top-three share when an entity is mentioned, in percentage points"',
    'complete -c aviary -f -s p -l preset -r -a "basic advanced strict geo" -d "Checker preset"',
    'complete -c aviary -f -l completion -r -a "bash zsh fish" -d "Shell completion format"',
    `complete -c aviary -f -l category -r -a "${categories.join(' ')}" -d "Checker categories"`,
  ];
  const argumentOptions = new Set([
    '-u',
    '--url',
    '--urls',
    '--sitemap',
    '--crawl',
    '-o',
    '--output',
    '--render',
    '--html',
    '--pdf',
    '--history',
    '--history-report',
    '--junit',
    '--sarif',
    '--timeout',
    '--wait-until',
    '--settle-ms',
    '--markdown',
    '--csv',
    '--bing-ai-csv',
    '--bing-ai-xlsx',
    '--bing-ai-baseline-csv',
    '--bing-ai-baseline-xlsx',
    '--bing-ai-query-baseline-csv',
    '--bing-ai-query-baseline-xlsx',
    '--bing-ai-topic-baseline-csv',
    '--bing-ai-topic-baseline-xlsx',
    '--google-ai-csv',
    '--google-ai-xlsx',
    '--google-ai-discover-csv',
    '--google-ai-discover-xlsx',
    '--google-ai-baseline-csv',
    '--google-ai-baseline-xlsx',
    '--google-ai-dimension-baseline-csv',
    '--google-ai-dimension-baseline-xlsx',
    '--geo-google-ai-citation-concordance-csv',
    '--geo-google-ai-citation-concordance-provider-csv',
    '--geo-google-ai-citation-concordance-html',
    '--geo-google-ai-citation-concordance-path-family-csv',
    '--geo-google-ai-citation-concordance-path-depth-sweep-csv',
    '--geo-google-ai-citation-concordance-baseline-json',
    '--geo-google-ai-citation-concordance-comparison-csv',
    '--geo-google-ai-citation-concordance-comparison-json',
    '--geo-google-ai-citation-concordance-comparison-html',
    '--geo-google-ai-citation-concordance-provider-comparison-csv',
    '--geo-google-ai-citation-concordance-path-depth',
    '--geo-google-surface-baseline-json',
    '--geo-google-surface-path-family-csv',
    '--geo-platform-baseline-json',
    '--geo-audit-json',
    '--geo-audit-baseline-json',
    '--geo-crawler-log',
    '--geo-crawler-path-families-csv',
    '--geo-crawler-path-families-json',
    '--geo-crawler-path-families-html',
    '--geo-crawler-path-family-audit-csv',
    '--geo-crawler-path-family-audit-json',
    '--geo-crawler-path-family-audit-html',
    '--geo-crawler-path-family-audit-comparison-csv',
    '--geo-crawler-path-family-audit-comparison-json',
    '--geo-crawler-path-family-audit-comparison-html',
    '--geo-crawler-path-family-comparison-csv',
    '--geo-crawler-path-family-comparison-json',
    '--geo-crawler-path-family-comparison-html',
    '--geo-crawler-ip-ranges',
    '--geo-answer-observations',
    '--geo-answer-baseline-observations',
    '--geo-answer-comparison-csv',
    '--geo-answer-provider-position-comparison-csv',
    '--geo-answer-cohorts-csv',
    '--geo-answer-cohort-comparison-csv',
    '--geo-answer-provider-pairs-csv',
    '--geo-answer-provider-prompt-overlap-csv',
    '--geo-answer-provider-prompt-source-overlap-csv',
    '--geo-answer-sample-mix-csv',
    '--geo-answer-cohort-period-standardization-csv',
    '--geo-answer-prompt-sampling-plan-csv',
    '--geo-answer-prompt-sampling-plan-json',
    '--geo-answer-prompt-plan-provider-pairs-csv',
    '--geo-answer-execution-context-csv',
    '--geo-answer-execution-context-coverage-csv',
    '--geo-answer-execution-context-comparison-csv',
    '--geo-answer-execution-context-trends-csv',
    '--geo-answer-length-profiles-csv',
    '--geo-answer-length-comparison-csv',
    '--geo-answer-length-trends-csv',
    '--geo-answer-prompt-plan-min-prompts',
    '--geo-answer-prompt-plan-owned-reach-margin',
    '--geo-answer-prompt-plan-min-jaccard',
    '--geo-answer-prompt-plan-max-paired-groups',
    '--geo-answer-prompt-plan-max-total-paired-groups',
    '--geo-answer-prompt-plan-total-allocation',
    '--geo-answer-prompt-plan-cohort-targets',
    '--geo-answer-cohort-standardization-csv',
    '--geo-answer-stability-csv',
    '--geo-answer-source-persistence-csv',
    '--geo-answer-citation-url-persistence-csv',
    '--geo-answer-cohort-trends-csv',
    '--geo-answer-audit-signals-csv',
    '--geo-answer-audited-owned-page-provider-inventory-csv',
    '--geo-answer-audited-owned-page-provider-inventory-html',
    '--geo-answer-audited-owned-page-provider-inventory-comparison-csv',
    '--geo-answer-audited-owned-page-provider-inventory-comparison-html',
    '--geo-answer-audited-owned-page-provider-inventory-comparison-json',
    '--geo-answer-audited-owned-pages-csv',
    '--geo-answer-audited-owned-page-comparison-csv',
    '--geo-answer-audited-owned-page-providers-csv',
    '--geo-answer-audited-owned-page-provider-comparison-csv',
    '--geo-answer-source-category',
    '--geo-answer-source-categories-csv',
    '--geo-answer-source-category-mapping-audit-csv',
    '--geo-answer-source-category-comparison-csv',
    '--geo-answer-source-category-mix-decomposition-csv',
    '--geo-answer-source-category-mix-decomposition-html',
    '--geo-answer-source-category-concentration-trends-csv',
    '--geo-answer-source-category-concentration-trends-html',
    '--geo-answer-source-category-share-trends-csv',
    '--geo-answer-source-category-share-trends-html',
    '--geo-answer-source-category-monthly-gates-json',
    '--fail-on-geo-answer-source-category-monthly-jsd-above',
    '--fail-on-geo-answer-source-category-monthly-hhi-rise-above',
    '--fail-on-geo-answer-source-category-monthly-top-three-hhi-rise-above',
    '--fail-on-geo-answer-source-category-monthly-hhi-above',
    '--fail-on-geo-answer-source-category-monthly-top-three-hhi-above',
    '--fail-on-geo-answer-source-category-monthly-min-events',
    '--fail-on-geo-answer-source-category-prompt-balanced-jsd-lower-ci-above',
    '--fail-on-geo-answer-source-category-prompt-balanced-jsd-min-prompts',
    '--geo-answer-source-category-prompt-balanced-jsd-gate-json',
    '--fail-on-geo-answer-source-category-share-drop',
    '--geo-answer-source-category-prompt-coverage-csv',
    '--geo-answer-source-category-prompt-details-csv',
    '--geo-answer-source-category-trends-csv',
    '--geo-answer-source-category-provider-pairs-csv',
    '--geo-answer-source-category-cooccurrence-csv',
    '--geo-answer-source-category-path-families-csv',
    '--geo-answer-source-category-path-family-comparison-csv',
    '--geo-answer-citation-positions-csv',
    '--geo-answer-domain-prompt-coverage-csv',
    '--geo-answer-source-rarefaction-csv',
    '--geo-answer-prompt-family-source-rarefaction-csv',
    '--geo-answer-prompt-family-source-rarefaction-sweep-csv',
    '--geo-answer-prompt-family-source-rarefaction-sweep-html',
    '--geo-answer-provider-prompt-family-source-overlap-csv',
    '--geo-answer-provider-prompt-family-source-overlap-html',
    '--geo-answer-provider-prompt-family-source-overlap-sweep-csv',
    '--geo-answer-provider-prompt-family-source-overlap-sweep-html',
    '--geo-answer-source-rarefaction-batch-size',
    '--geo-answer-domain-prompt-coverage-comparison-csv',
    '--geo-answer-domain-paired-reach-comparison-csv',
    '--geo-answer-domain-paired-reach-comparison-json',
    '--fail-on-geo-answer-domain-paired-reach-drop',
    '--fail-on-geo-answer-domain-paired-reach-alpha',
    '--fail-on-geo-answer-domain-paired-reach-min-prompts',
    '--geo-answer-domain-paired-reach-gate-json',
    '--geo-answer-source-diversity-uncertainty-csv',
    '--geo-answer-source-diversity-uncertainty-html',
    '--geo-answer-source-diversity-comparison-csv',
    '--geo-answer-source-diversity-comparison-html',
    '--geo-answer-provider-source-divergence-csv',
    '--geo-answer-source-portfolio-drift-csv',
    '--geo-answer-source-portfolio-drift-html',
    '--geo-answer-source-portfolio-drift-json',
    '--geo-answer-source-portfolio-attribution-csv',
    '--geo-answer-source-portfolio-attribution-json',
    '--geo-answer-source-portfolio-attribution-html',
    '--geo-answer-owned-source-share-gate-csv',
    '--geo-answer-owned-source-share-gate-json',
    '--geo-answer-source-network-csv',
    '--geo-answer-source-network-comparison-csv',
    '--geo-answer-rank-weighted-source-network-csv',
    '--geo-answer-rank-weighted-source-network-comparison-csv',
    '--geo-answer-source-network-html',
    '--geo-answer-source-network-comparison-html',
    '--geo-answer-provider-source-network-overlap-csv',
    '--geo-answer-provider-source-network-edge-drift-csv',
    '--geo-answer-provider-source-network-edge-drift-html',
    '--geo-answer-provider-source-network-edge-comparison-csv',
    '--geo-answer-provider-source-network-edge-html',
    '--geo-answer-owned-source-network-gaps-csv',
    '--geo-answer-prompt-similarity-csv',
    '--geo-answer-prompt-families-csv',
    '--geo-answer-prompt-families-html',
    '--geo-answer-prompt-family-influence-csv',
    '--geo-answer-prompt-family-influence-html',
    '--geo-answer-prompt-family-threshold-sweep-csv',
    '--geo-answer-prompt-family-threshold-sweep-html',
    '--geo-answer-prompt-similarity-threshold',
    '--geo-answer-prompt-family-threshold',
    '--geo-answer-citation-date-alignment-csv',
    '--geo-answer-owned-rank-csv',
    '--geo-answer-owned-prompt-coverage-csv',
    '--geo-answer-owned-prompt-reach-period-csv',
    '--geo-answer-owned-prompt-opportunities-csv',
    '--geo-answer-competitive-gaps-csv',
    '--geo-answer-provider-owned-gaps-csv',
    '--geo-answer-provider-owned-gap-comparison-csv',
    '--geo-answer-competitive-gap-comparison-csv',
    '--geo-answer-owned-rank-comparison-csv',
    '--geo-answer-owned-prompt-rank-comparison-csv',
    '--geo-answer-co-citation-csv',
    '--geo-answer-co-citation-comparison-csv',
    '--geo-answer-entity-mentions-csv',
    '--geo-answer-entity-prompt-details-csv',
    '--geo-answer-entity-prompt-provider-pairs-csv',
    '--geo-answer-entity-prompt-comparison-csv',
    '--geo-answer-entity-co-mentions-csv',
    '--geo-answer-entity-co-mention-comparison-csv',
    '--geo-answer-entity-citation-domains-csv',
    '--geo-answer-entity-citation-pages-csv',
    '--geo-answer-entity-source-categories-csv',
    '--geo-answer-entity-source-category-comparison-csv',
    '--geo-answer-entity-citation-domain-comparison-csv',
    '--geo-answer-entity-citation-page-comparison-csv',
    '--geo-answer-entity-citation-position-comparison-csv',
    '--geo-answer-entity-opportunities-csv',
    '--geo-answer-entity-prompt-matched-association-csv',
    '--geo-answer-entity-prompt-matched-association-html',
    '--geo-answer-entity-path-families-csv',
    '--geo-answer-entity-path-family-monthly-csv',
    '--geo-answer-entity-path-family-comparison-csv',
    '--geo-answer-path-family-csv',
    '--geo-answer-path-family-cohorts-csv',
    '--geo-answer-path-family-trends-csv',
    '--geo-answer-path-family-cohort-comparison-csv',
    '--geo-answer-path-family-comparison-csv',
    '--geo-answer-crawler-report',
    '--geo-answer-crawler-origin',
    '--geo-answer-crawler-matches-csv',
    '--geo-answer-path-depth',
    '--geo-answer-source-category',
    '--geo-answer-source-categories-csv',
    '--geo-answer-source-category-mapping-audit-csv',
    '--geo-answer-owned-domain',
    '--geo-answer-entity',
    '--geo-crawler-sitemap',
    '--geo-robots-txt',
    '--geo-robots-baseline-txt',
    '--geo-robots-sitemap',
    '--geo-summary-output',
    '--baseline',
    '--comparison-output',
    '-c',
    '--config',
    '--viewport',
    '--max-urls',
    '--max-depth',
    '--max-crawl-page-bytes',
    '--max-crawl-bytes',
    '--concurrency',
    '--watch',
    '--timeout',
    '--fail-below-score',
    '--fail-on-geo-crawler-path-family-failure-rise',
    '--fail-on-geo-answer-owned-citation-drop',
    '--fail-on-geo-answer-owned-source-share-drop',
    '--fail-on-geo-answer-owned-source-share-drop-lower-ci',
    '--fail-on-geo-answer-owned-source-share-sign-test-alpha',
    '--fail-on-geo-answer-owned-source-share-min-prompts',
    '--fail-on-geo-answer-owned-reach-bound-drop',
    '--fail-on-geo-answer-unknown-owned-observation-share',
    '--fail-on-geo-answer-unknown-owned-prompt-share',
    '--fail-on-geo-answer-unknown-owned-state-share-rise',
    '--fail-on-geo-answer-owned-top-three-drop',
    '--fail-on-geo-answer-owned-first-position-drop',
    '--fail-on-geo-answer-owned-prompt-balanced-first-position-drop',
    '--fail-on-geo-answer-owned-prompt-balanced-first-position-drop-lower-ci',
    '--fail-on-geo-answer-owned-prompt-balanced-top-three-drop',
    '--fail-on-geo-answer-owned-prompt-balanced-top-three-drop-lower-ci',
    '--fail-on-geo-answer-owned-prompt-balanced-rank-min-matched-prompts',
    '--fail-on-geo-answer-owned-prompt-balanced-mrr-drop',
    '--fail-on-geo-answer-owned-prompt-balanced-mrr-drop-lower-ci',
    '--fail-on-geo-answer-length-owned-top-three-drop',
    '--fail-on-geo-answer-length-owned-top-three-drop-lower-ci',
    '--fail-on-geo-answer-length-owned-first-position-drop',
    '--fail-on-geo-answer-length-owned-first-position-drop-lower-ci',
    '--fail-on-geo-answer-length-owned-mrr-drop',
    '--fail-on-geo-answer-length-owned-mrr-drop-lower-ci',
    '--fail-on-geo-answer-length-owned-rank-min-matched-prompts',
    '--fail-on-geo-answer-entity-mention-drop',
    '--fail-on-geo-answer-entity-owned-top-three-drop',
    '--fail-on-geo-answer-path-family-coverage-drop',
    '--fail-on-geo-answer-path-family-prompt-coverage-drop',
    '--fail-on-geo-answer-path-family-over-index-drop',
    '--fail-on-geo-answer-entity-path-family-prompt-coverage-drop',
    '--fail-on-geo-answer-entity-path-family-top-three-drop',
    '--fail-on-geo-answer-entity-citation-page-prompt-coverage-drop',
    '--fail-on-geo-answer-entity-citation-page-top-three-drop',
    '--fail-on-geo-answer-entity-prompt-mention-drop',
    '--fail-on-geo-answer-entity-prompt-balanced-mention-drop',
    '--fail-on-geo-answer-entity-prompt-min-matched-prompts',
    '--fail-on-geo-answer-provider-prompt-overlap-below',
    '--fail-on-geo-answer-provider-min-prompts',
    '--fail-on-geo-answer-provider-min-matched-prompts',
    '--fail-on-geo-answer-owned-prompt-coverage-drop',
    '--fail-on-geo-answer-cohort-owned-prompt-coverage-drop',
    '--fail-on-geo-answer-cohort-owned-mrr-drop',
    '--fail-on-geo-answer-cohort-owned-mrr-min-prompts',
    '--fail-on-geo-answer-cohort-monthly-owned-mrr-drop',
    '--fail-on-geo-answer-cohort-monthly-owned-mrr-min-prompts',
    '--fail-on-geo-answer-cohort-monthly-paired-mrr-drop',
    '--fail-on-geo-answer-cohort-monthly-paired-mrr-drop-lower-ci',
    '--fail-on-geo-answer-cohort-monthly-paired-mrr-min-matched-prompts',
    '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop',
    '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-drop-lower-ci',
    '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-decline',
    '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-holm-alpha',
    '--fail-on-geo-answer-cohort-monthly-owned-prompt-coverage-min-matched-prompts',
    '--fail-on-geo-answer-sample-mix-divergence',
    '--fail-on-geo-answer-cohort-standardized-citation-drop',
    '--fail-on-geo-answer-cohort-standardized-owned-prompt-coverage-drop',
    '--geo-crawler-token',
    '--geo-ai-referral-source',
    '--geo-crawler-origin',
    '--geo-crawler-sitemap-max-urls',
    '--geo-robots-origin',
    '--geo-robots-sitemap',
    '--geo-robots-token',
    '--geo-sitemap',
    '--geo-sitemap-max-urls',
    '--geo-path-depth',
    '--geo-crawler-path-depth',
    '--geo-answer-path-depth',
    '--geo-answer-prompt-family-threshold',
    '-p',
    '--preset',
    '--category',
    '--completion',
    '--fail-on-geo-change-signal',
    '--fail-on-geo-change-url',
    '--fail-on-geo-change-transition',
  ]);
  const descriptiveFishFlags = new Set(['--fail-on-geo-answer-prompt-plan-miss']);
  for (const flag of FLAGS.filter(
    (item) => !argumentOptions.has(item) && !descriptiveFishFlags.has(item)
  )) {
    if (flag.startsWith('-') && flag.length === 2) {
      lines.push(`complete -c aviary -f -s ${flag.slice(1)} -d "Aviary option"`);
    } else {
      lines.push(`complete -c aviary -f -l ${flag.slice(2)} -d "Aviary option"`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/** Render a shell completion definition for installation in the user's shell config. */
export function renderShellCompletion(shell: CompletionShell, categories: string[]): string {
  if (shell === 'bash') return bashCompletion(categories);
  if (shell === 'zsh') return zshCompletion(categories);
  return fishCompletion(categories);
}
